policies:
  # The following policies are designed to work from GitHub action workflows.
  # This means that before running any Updatecli command, we need the two following environment variables set:
  # 
  #   GITHUB_TOKEN: Set to a personal access token
  #   GITHUB_ACTOR: Set to the username associated with the GITHUB_TOKEN
  # 
  # Instruction to retrieve your PAT is documented on https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens
  - name: Handle docusaurus versioning
    policy: ghcr.io/olblak/rancherlabs-policies/docusaurus/versioning:0.1.0@sha256:6693eee54400675304b58e38df91681b4da0358a9ddb3266825ffb78ce9a9a24
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/fleet.yaml
  - name: Handle releasepost
    policy: ghcr.io/olblak/rancherlabs-policies/docusaurus/releasepost:0.4.1@sha256:97f85210e352d62d7154d9f3779ffb3bf4eac96a4befca2b616e400529c50a3e
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/fleet.yaml
  - name: Handle Updatecli policies
    policy: ghcr.io/updatecli/policies/autodiscovery/updatecli:0.5.0@sha256:df7fb3a9e3348a9749527edf867be1090f452f9ee0c2116aab6de39729850d53
    values:
      - updatecli/values.d/scm-2.yaml
